# Numpy
* NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations

In [1]:
import numpy as np
# Create array using numpy
# Create 1D array
arr1=np.array([1,2,3,4,5])
print(arr1, type(arr1))
arr1.shape

[1 2 3 4 5] <class 'numpy.ndarray'>


(5,)

In [5]:
# 1D Array
arr2=np.array([1,2,3,4,5,6])
arr2.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [7]:
# 2D Array
arr3=np.array([[1,2,3],[4,5,6]])
print(arr3,type(arr3),arr3.shape)

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'> (2, 3)


In [9]:
np.arange(1,10,2).reshape(5,1)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
# Identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
# Attributes of Numpy Array
arr=np.array([[1,2,3,4],[5,6,7,8]])

print("Array :", arr)
print("Shape of Array :",arr.shape)
print("No of Dimensions :",arr.ndim)
print("Size (No of Elements):",arr.size)
print("Data Type", arr.dtype)
print("Item Size (in bytes)", arr.itemsize)

Array : [[1 2 3 4]
 [5 6 7 8]]
Shape of Array : (2, 4)
No of Dimensions : 2
Size (No of Elements): 8
Data Type int64
Item Size (in bytes) 8


In [14]:
# Numpy Vectorized Operations
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

# Element Wise Operations
# Addition
print("Addition :",arr1+arr2)

# Substraction
print("Substraction :",arr1-arr2)

# Multiplication
print("Multiplication :",arr1*arr2)

# Division
print("Division :",arr1/arr2)

Addition : [ 7  9 11 13 15]
Substraction : [-5 -5 -5 -5 -5]
Multiplication : [ 6 14 24 36 50]
Division : [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [15]:
# Universal Functions
arr=np.array([1,2,3,4,5])

#sqrt
print("Square Root :",np.sqrt(arr))

# Exponential
print("Exponential :",np.exp(arr))

# Sine
print(np.sin(arr))

Square Root : [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential : [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [16]:
# Array Slicing and Indexing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array \n",arr)

Array 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [20]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [21]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [22]:
# Modify Array Elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [23]:
arr[1:]=100
arr

array([[100,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [25]:
# Statistical Concepts - Normalization
# Mean=0, Standared Deviation=1
data=np.array([1,2,3,4,5])

# Calculate Mean and Standared Deviation
mean=np.mean(data)
sd=np.std(data)

# Normalized Data
normalized_data=(data-mean)/sd
print("Normalized Data :",normalized_data)

Normalized Data : [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [26]:
data=np.array([9,8,7,6,5])

# Mean
mean=np.mean(data)
median=np.median(data)
sd=np.std(data)
variance=np.var(data)

print("Mean :",mean)
print("Median :", median)
print("Standared Deviation :",sd)
print("Variance :",variance)

Mean : 7.0
Median : 7.0
Standared Deviation : 1.4142135623730951
Variance : 2.0


In [28]:
# Logical Operation
data=np.array([1,2,3,4,5])
data[(data<=5)&(data>3)]

array([4, 5])